import treesitter from 'eslint-config-treesitter';

export default [
  ...treesitter,
  {
    ignores: [
      '**/node_modules/**',
      '**/out/**',
      'src/**', // Generated by tree-sitter
    ],
  },
  {
    rules: {
      // Allow underscore-prefixed variables to be unused
      'no-unused-vars': [
        'error',
        {
          args: 'none',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Disable formatting rules that conflict with Prettier
      indent: 'off',
      quotes: 'off',
      semi: 'off',
      'comma-dangle': 'off',
      'object-curly-spacing': 'off',
      'operator-linebreak': 'off',
      'quote-props': 'off',
      'space-before-function-paren': 'off',
      'block-spacing': 'off',
      'brace-style': 'off',
      'comma-spacing': 'off',
      'keyword-spacing': 'off',
      'key-spacing': 'off',
      'no-trailing-spaces': 'off',
      'no-multiple-empty-lines': 'off',
      'padded-blocks': 'off',
      'semi-spacing': 'off',
      'array-bracket-spacing': 'off',
      'computed-property-spacing': 'off',
      'func-call-spacing': 'off',
      'space-before-blocks': 'off',
      'switch-colon-spacing': 'off',
      'arrow-parens': 'off',
      'generator-star-spacing': 'off',
      'rest-spread-spacing': 'off',
      'yield-star-spacing': 'off',
    },
  },
];
